name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env: 
  REGISTRY: ghcr.io
  SERVER_SIDE_BACKEND_URL: https://otel-cookbook.com # will be overwritten through docker compose file to point to localhost on the VM
  NEXT_PUBLIC_BACKEND_URL: https://otel-cookbook.com
  TAG: 0.1.0-${{ github.run_id }} # update tag for a new version release

jobs:
  build-frontend-docker-image:
    runs-on: ubuntu-latest
    name: Build Frontend Docker Image
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    environment:
      name: prod 
    env: 
      IMAGE_NAME: ${{ github.repository }}/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          context: ./frontend
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          build-args: |
            "NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }}"
            "SERVER_SIDE_BACKEND_URL=${{ env.SERVER_SIDE_BACKEND_URL }}"
            "GH_API_TOKEN=${{ secrets.GH_API_TOKEN }}"

  build-backend-docker-image:
    runs-on: ubuntu-latest
    name: Build Backend Docker Image
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    environment:
      name: prod 
    env: 
      IMAGE_NAME: ${{ github.repository }}/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          context: ./backend
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max

  validate-nginx-config:
    runs-on: ubuntu-latest
    name: Validate Nginx Config
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gixy Docker command
        run: |
          docker run --rm -v "${{ github.workspace }}/deployment/nginx/conf.d/app.conf:/etc/nginx/conf/nginx.conf" yandex/gixy /etc/nginx/conf/nginx.conf

  check-port:
    runs-on: ubuntu-latest
    name: Check if Port 22 is Open
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    outputs:
      port_open: ${{ steps.check.outputs.port_open }}
    steps:
      - name: Check Port 22
        id: check
        run: |
          if nc -z -w5 "${{ secrets.VPS_IP }}" 22; then
            echo "Port 22 is open."
            echo "port_open=true" >> $GITHUB_OUTPUT
          else
            echo "::warning::Port 22 is not open on ${{ secrets.VPS_IP }}. Please open port 22 before proceeding."
            echo "port_open=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: 
      - build-frontend-docker-image
      - build-backend-docker-image
      - check-port
      - validate-nginx-config
    if: ${{ github.event.workflow_run.head_branch == 'main' && needs.check-port.outputs.port_open == 'true' }}
    environment:
      name: prod 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Substitute EnvVars
        run: |
          envsubst < deployment/docker-compose.yml > deployment/docker-compose.subst.yml

      - name: Copy Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "deployment/*"
          target: "deployments/${{ github.repository }}/"

      - name: Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd deployments/${{ github.repository }}/deployment

            REQUIRED_NGINX_FILES="nginx/certs/cf-origin.crt nginx/certs/cf-origin.key nginx/conf.d/app.conf"
            for file in $REQUIRED_NGINX_FILES; do
              if [ ! -f "$file" ]; then
                echo "Error: Required NGINX file '$file' not found. Ensure those are present before starting the app."
                exit 1
              fi
            done

            export GH_API_TOKEN=${{ secrets.GH_API_TOKEN }}
            docker compose -f docker-compose.subst.yml pull
            # docker compose -f docker-compose.subst.yml up -d