name: E2E

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8am UTC
  # workflow_run:
  #   workflows: ["CD"]
  #   types:
  #     - completed

jobs:
  prepare-e2e: # fetches all available OpenTelemetry Collector components
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.get-collector-components.outputs.result }}
    steps: 
      - id: get-collector-components
        name: Get collector components 
        run: |
          res=$(curl -s https://otel-cookbook.com/server/otelcol/components | jq -c .)
          echo "result=$res" >> $GITHUB_OUTPUT      
 
  e2e:
    needs: prepare-e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        request:
          - name: binary-debug-mode-all-components
            body: >-
              {"BuilderConfig":{"collectorName":"my-otel-collector","version":"","description":"collector description","outputPath":"./otelcol-dev","debugMode":true,"runConfig":"binary"},"CollectorConfig":{"Ports":"4317","DockerImageName":"my-otel-collector","Manifest":"# Minimal OpenTelemetry Collector Configuration\nreceivers:\n  otlp:\n    protocols:\n      grpc: # Enables OTLP over gRPC on the default port 4317\n      http: # Enables OTLP over HTTP on the default port 4318\n\nexporters:\n  debug:\n    verbosity: detailed\n\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      exporters: [debug]\n    metrics:\n      receivers: [otlp]\n      exporters: [debug]\n    logs:\n      receivers: [otlp]\n      exporters: [debug]"}}

          - name: docker-debug-mode-all-components
            body: >-
              {"BuilderConfig":{"collectorName":"my-otel-collector","version":"","description":"collector description","outputPath":"./otelcol-dev","debugMode":true,"runConfig":"docker"},"CollectorConfig":{"Ports":"4317","DockerImageName":"my-otel-collector","Manifest":"# Minimal OpenTelemetry Collector Configuration\nreceivers:\n  otlp:\n    protocols:\n      grpc: \n        endpoint: \"0.0.0.0:4317\"\n      http: \n        endpoint: \"0.0.0.0:4318\"\n\nexporters:\n  debug:\n    verbosity: detailed\n\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      exporters: [debug]\n    metrics:\n      receivers: [otlp]\n      exporters: [debug]\n    logs:\n      receivers: [otlp]\n      exporters: [debug]"}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Test - ${{ matrix.request.name }}
        run: |
          #!/usr/bin/env bash
          # set -euo pipefail
          
          echo "Components JSON:"
          echo '${{ needs.prepare-e2e.outputs.components }}' > components.json
          cat components.json
          
          jq -n \
            --argjson base '${{ matrix.request.body }}' \
            --argjson components '${{ needs.prepare-e2e.outputs.components }}' \
            '$base * $components' > request.json

          curl 'https://otel-cookbook.com/server/otelcol/config/start' \
              -H 'cache-control: no-cache' \
              -H 'content-type: application/json' \
              -H 'origin: https://otel-cookbook.com' \
              -H 'referer: https://otel-cookbook.com/preview' \
              --data-raw "$(cat request.json)" > run.sh

          chmod +x run.sh
          cat run.sh

          export PATH="$HOME/go/bin:$PATH"

          ./run.sh &
          SERVER_PID=$!

          max_attempts=240
          attempt=1
          while ! { nc -z localhost 4317 && nc -z localhost 4318; } ; do
            echo "Waiting for collector to be ready (attempt $attempt)..."
            sleep 8
            if [ $attempt -ge $max_attempts ]; then
                echo "Error: Collector did not become available after $((max_attempts * 2)) seconds." >&2
                kill $SERVER_PID
                exit 1
            fi
            attempt=$((attempt + 1))
          done

          echo "Collector is up and running."

          go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest
          export PATH="$HOME/go/bin:$PATH"

          telemetrygen traces --traces 5 --otlp-insecure

          sleep 5

          echo "Stopping the HTTP server..."
          kill $SERVER_PID
          wait $SERVER_PID || true
          echo "HTTP server stopped."
