name: CI – Build, Test, and Docker (Frontend)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  SERVER_SIDE_BACKEND_URL: https://otel-cookbook.com # will be overwritten through docker compose file to point to localhost on the VM
  NEXT_PUBLIC_BACKEND_URL: https://otel-cookbook.com

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    name: Build, Lint, and Test Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Test
      #   run: npm test